### PR TITLE
DNM: Test ansible linting

### PR DESCRIPTION
**Pull request by ra-beer**
Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>

### CODE REVIEW

**Comment by ra-beer** [comment]
recheck

**Comment by ra-beer** [comment]
recheck

**Comment by ra-beer** [comment]
recheck

**Comment by ra-beer** [comment]
recheck

**Comment by tibeer** [comment]
recheck

**Comment by tibeer** [comment]
recheck

**Comment by ra-beer** [comment]
No longer needed.

**Pull request closed without merging**
